[package]
name = "quickcv"
version = "0.1.0"
description = "quickCV desktop app"
authors = ["quickCV"]
license = "MIT"
repository = ""
edition = "2021"
rust-version = "1.86"

[build-dependencies]
tauri-build = { version = "2.0.1", features = [] }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = { version = "2.0.5", features = ["tray-icon"] }
tauri-plugin-dialog = "2.0.1"
tauri-plugin-opener = "2.0.1"
tauri-plugin-autostart = "2.0.1"
tauri-plugin-global-shortcut = "2.3.1"
chrono = { version = "0.4.39", features = ["clock"] }
reqwest = { version = "0.12.9", default-features = false, features = ["json", "rustls-tls"] }
uuid = { version = "1.11.0", features = ["v4", "serde"] }
arboard = "3.4.1"
rdev = "0.5.3"
windows = { version = "0.61.3", features = [
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
  "Win32_UI_WindowsAndMessaging",
  "Win32_UI_Accessibility",
  "Win32_System_Com",
  "Win32_System_Ole",
  "Win32_Security",
  "Win32_System_Threading",
  "Win32_UI_Input_Ime",
  "Win32_UI_Input_KeyboardAndMouse"
] }
